const cursos = [
    {
      curso: "HTML e CSS",
      descricao: "Aprenda HTML e CSS!",
      duracao: "1 mês",
      valor: 500,
    },
    {
      curso: "JavaScript",
      descricao: "Aprenda JavaScript!",
      duracao: "2 meses",
      valor: 900,
    },
    {
      curso: "APIs REST",
      descricao: "APIs REST é tão legal!",
      duracao: "6 meses",
      valor: 2000,
    },
  ];
  
  const turmas = [
    {
      turma: "Hipátia",
      curso: "JavaScript",
      inicio: "30/11/2022",
      fim: "30/01/2023",
      numEstudantes: 150,
      periodo: "Noturno",
      concluida: false,
    },
    {
      turma: "Sibyla",
      curso: "JavaScript",
      inicio: "30/10/2022",
      fim: "30/12/2022",
      numEstudantes: 200,
      periodo: "Integral",
      concluida: false,
    },
    {
      turma: "Curie",
      curso: "HTML e CSS",
      inicio: "15/09/2022",
      fim: "15/10/2022",
      numEstudantes: 180,
      periodo: "Noturno",
      concluida: true,
    },
    {
      turma: "Zhenyi",
      curso: "HTML e CSS",
      inicio: "01/11/2022",
      fim: "01/01/2023",
      numEstudantes: 80,
      periodo: "Integral",
      concluida: false,
    },
    {
      turma: "Clarke",
      curso: "HTML e CSS",
      inicio: "04/07/2022",
      fim: "04/09/2022",
      numEstudantes: 200,
      periodo: "Noturno",
      concluida: true,
    },
    {
      turma: "Blackwell",
      curso: "APIs Rest",
      inicio: "20/03/2022",
      fim: "20/06/2022",
      numEstudantes: 100,
      periodo: "Integral",
      concluida: true,
    },
    {
      turma: "Elion",
      curso: "APIs Rest",
      inicio: "12/01/2022",
      fim: "12/06/2022",
      numEstudantes: 200,
      periodo: "Noturno",
      concluida: true,
    },
    {
      turma: "Burnell",
      curso: "APIs Rest",
      inicio: "18/10/2022",
      fim: "18/04/2023",
      numEstudantes: 90,
      periodo: "Integral",
      concluida: false,
    },
  ];
  
  const estudantes = [
    {
      estudante: "Timothee Chalamet",
      turma: "Hipátia",
      curso: "JavaScript",
      valor: 900,
      numParcelas: 9,
      desconto: false,
      valorParcela: 100,
    },
    {
      estudante: "Halle Berry",
      turma: "Burnell",
      curso: "APIsRest",
      valor: 2000,
      numParcelas: 4,
      desconto: false,
      valorParcela: 500,
    },
    {
      estudante: "Lashana Lynch",
      turma: "Zhenyi",
      curso: "HTML e CSS",
      valor: 500,
      numParcelas: 1,
      desconto: true,
      valorParcela: 500,
    },
  ];
  